Keyteq\Bundle\CloudinaryMetaIndexer\Entity\CloudinaryResource:
    type: entity
    table: cloudinary_resources
    fields:
        publicId:
            type: string
            id: true
            strategy: NONE
        format:
            type: string
            nullable: true
        version:
            type: string
        resourceType:
            type: string
        type:
            type: string
        createdAt:
            type: date
        bytes:
            type: integer
        width:
            type: integer
            nullable: true
        height:
            type: integer
            nullable: true
        url:
            type: text
        secureUrl:
            type: text
        tags:
            type: array
        context:
            type: json
            nullable: true
