Keyteq\Bundle\CloudinaryMetaIndexer\Document\CloudinaryResource:
    fields:
        public_id:
            type: string
        format:
            type: string
        version:
            type: string
        resource_type:
            type: string
        type:
            type: string
        created_at:
            type: string
        bytes:
            type: string
        width:
            type: string
        height:
            type: string
        url:
            type: string
        secure_url:
            type: string