ezpublish:
    system:
        default:
            content_view:
                full:
                    '%keyteq_cloudinary_meta_indexer.content_type_identifier%':
                        controller: '%keyteq_cloudinary_meta_indexer.controller.full%'
                        template: "KeyteqCloudinaryMetaIndexerBundle:content/full:cloudinary_page.html.twig"
                        match:
                            Identifier\ContentType: '%keyteq_cloudinary_meta_indexer.content_type_identifier%'