imports:
    - { resource: controllers.yml }
services:
    keyteq.cloudinary_meta_indexer.adapter.cloudinary:
        class: Keyteq\Bundle\CloudinaryMetaIndexer\Adapter\CloudinaryAdapter
        arguments:
            - '%cloudinary_meta_indexer.config%'
    keyteq.cloudinary_meta_indexer.storage:
        class: Keyteq\Bundle\CloudinaryMetaIndexer\Manager\StorageManager
        arguments:
            - '@file_locator'
            - '@keyteq.cloudinary_meta_indexer.adapter.cloudinary'
            - '%cloudinary_meta_indexer.config%'

    keyteq.cloudinary_meta_indexer.sync:
        class: Keyteq\Bundle\CloudinaryMetaIndexer\Manager\SyncManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@keyteq.cloudinary_meta_indexer.adapter.cloudinary'
            - '%cloudinary_meta_indexer.config%'
            - '@ezpublish.api.repository'
            - '%keyteq_cloudinary_meta_indexer.content_type_identifier%'
            - '@ezplatform.http_cache.purge_client'
            - "@?logger"
