imports:
    - { resource: controllers.yml }
services:
    keyteq.cloudinary_meta_indexer.storage:
        lazy: true
        class: Keyteq\Bundle\CloudinaryMetaIndexer\Manager\StorageManager
        arguments:
            - '@file_locator'
            - '%cloudinary_meta_indexer.config%'

    keyteq.cloudinary_meta_indexer.sync:
        lazy: true
        class: Keyteq\Bundle\CloudinaryMetaIndexer\Manager\SyncManager
        arguments:
            - '@keyteq.cloudinary_meta_indexer.storage'
            - '%cloudinary_meta_indexer.config%'
            - "@?logger"
